### PR TITLE
Officially support Python 3.5 to 3.8

### PR DESCRIPTION
**Pull request by hartwork**

### CODE REVIEW

**Comment by wong2** [comment]
I think we should bump a major version for dropping python2 support

**Comment by hartwork** [comment]
Are you suggesting that I should bump the version inside of this pull request?

**Comment by wong2** [comment]
Yes you can do it in a separate commit

**Comment by hartwork** [comment]
Okay sure, done.

**Comment by hartwork** [comment]
@wong2 what are your plans on releasing 1.0.0?

**Comment by wong2** [comment]
It is published

**Comment by hartwork** [comment]
> It is published

Okay thanks!

**Pull request merged**
