### PR TITLE
Setup Poetry and introduce type hints

### LINKED ISSUE #41: Use poetry to manage the project
https://python-poetry.org

### PR DESCRIPTION
**Pull request by MaxG87**
This PR will introduce Poetry as only tool to manage the project and add extensive type hints.

The part about Poetry is quite uncontroversial, since there is already an open ticket for that. Thus, this PR fixes #41.

The introduction of type hints is what brought me here. I would like to have them in another project. Unfortunately, this introduces severe complexity into the code base. I tried to mitigate this by always returning a list of selections, but the problem still remains. Since it only reflects the complexity inherent to the Picker class, I decided to proceed anyways. Some further improvements might be possible by using `@overload` annotations from `typing`, but I wanted to get some feedback before I proceed with that.

Fortunately, most of the type hint complexity affects the `Picker` class itself. For someone who only uses the `pick` function, everything is quite obvious.

I hope that this PR is helpful to you. If you feel uncomfortable about the type hint stuff, I could separate this into another PR and refine it there.

### CODE REVIEW

**Comment by MaxG87** [comment]
I managed to simplify the type annotations a bit. Now the `options_func_map` is not an optional function anymore, but a mandatory with a default value. This does affect how users interact with the framework. However, it allows to use `OPTIONS_MAP_VALUE_T` throughout, without having to use the default `Tuple[str, int]` anywhere.

**Comment by wong2** [comment]
nice, I'll have a look soon

**Comment by wong2** [comment]
I'd rather have this splitted to two seperate PRs

**Comment by wong2** [comment]
Hi, could you please make the follow-up PR?

**Comment by wong2** [comment]
Also I'm considering refactor the project with blessed https://github.com/wong2/pick/issues/58

**Pull request closed without merging**
