### PR TITLE
Support initial selection (fixes #37)

### LINKED ISSUE #37: Support for initial selection?
Hi, thanks for sharing `pick` as software libre! :pray: 

In my scenario I need to pre-select some options, primarily for multi-select mode. [What I currently do](https://github.com/hartwork/git-delete-merged-branches/blob/04fdeb4eec4223d03af387e183baa7d50e6b3607/git_delete_merged_branches/_multiselect.py#L7-L16) at [git-delete-merged-branches](https://github.com/hartwork/git-delete-merged-branches) is this:

```python
from pick import Picker

class _PickerWithPreselection(Picker):
    def __init__(self, options, initial_selection=None, **kwargs):
        super().__init__(options, **kwargs)
        if initial_selection is not None:
            self.all_selected = sorted(
                set(i for i in initial_selection if isinstance(i, int) and 0 <= i < len(options)))
            if self.all_selected and kwargs.get('default_index') is None:
                self.index = self.all_selected[0]
```

Is that something you'd want to integrate with `pick`?

Best, Sebastian

### PR DESCRIPTION
**Pull request by hartwork**
Fixes #37

### CODE REVIEW

**Comment by hartwork** [comment]
@wong2 what do you think?

**Comment by wong2** [comment]
Yeah I'll do that, but please wait for a few days

**Comment by hartwork** [comment]
Okay, see you in a few days :+1:

**Comment by hartwork** [comment]
@wong2 it's been a while, any news?

**Comment by hartwork** [comment]
Closing because of no reply and lost interest

**Pull request closed without merging**
