### PR TITLE
Multiselect

### PR DESCRIPTION
**Pull request by eth0izzle**
- Added the ability to select more than one item. Default selector key is SPACE or RIGHT ARROW.
- Change the style of chosen items with constructor argument `chosen_indicator`. Default is BOLD
- Introduced two new chainable helper methods that either return a tuple(option, index) or list of tuples : `one()`, `many()`, e.g.`option, index = picker(options, title).one()` or `chosen_options = picker(options, title).many()` or call `Picker` directly with `start()` to get a variable return type
- `min_select` option to force a user to choose an option: `picker(options, title, min_select=2)` means 2 items must be chosen before returning
- Updated README, examples, tests

### CODE REVIEW

**Comment by wong2** [comment]
@eth0izzle thanks for this!

one of the rules I follow when developing a package is to make the most common usage simple, and for `pick`, that is "select one item from a list", and the new API `option, index = pick(options, title, min_select=1).one()` is just too complicated for me
maybe we could use `min_select` to distinguish if it's a multi select? eg:
`option, index = pick(options, title)` for one item, and 
`options = pick(options, title, min_select=2)` for multi select (`min_select>=2`)

**Comment by eth0izzle** [comment]
@wong2 you can do that if you wish, `one()` and `many()` just sets multiselect_allow=True/False which you can pass in the constructor: `chosen_options = pick(options, title, multiselect_allow=True).start()`.

**Comment by wong2** [comment]
@eth0izzle sorry for the delay. in my design, the `pick` method is just a helper function to initialize a `Picker` and start it, so `pick(...).start()` doesn't make sense to me. Can we just keep `pick` as before and add another `pick_multi(...)` for multi select? I think this is more comprehensive, considering one returns a tuple, and another returns a list of tuples

**Comment by wong2** [comment]
thanks for your work! I've merged another PR implementing this feature.

**Pull request closed without merging**
