### PR TITLE
Behavioral change for multi_select

### PR DESCRIPTION
**Pull request by comister**
Behavioral change for multi_select: If multi select is used a simple return without having anything selected with Space will not do anything anymore, otherwise the returned list of sets is empty

### CODE REVIEW

**Comment by wong2** [comment]
maybe there are use cases where the user _can_ select nothing?

**Comment by comister** [comment]
@wong2 Hmm, maybe, so having another parameter something like mandatory flag or min-count-selected or similar would help here, I believe ?

**Comment by wong2** [comment]
@comister yeah, I think `min-count-selected` should do the trick

**Comment by comister** [comment]
ok, let me add that in the next days, will shoot it in then !

**Comment by comister** [comment]
Here we go, tried to update everything I could think of, please check !

**Comment by comister** [comment]
@wong2 , are we all good with that ?

**Comment by wong2** [comment]
would you like to replace `min_count_selected` with `min_selection_count`?

**Comment by comister** [comment]
@wong2 No problem, just done !

**Comment by wong2** [comment]
🍰  thanks!

**Pull request merged**
